version: '3'

services:
  web:
    container_name: capybara_django_web
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./www:/www
    ports:
      - 8000:8000
    tty: true
#    image: app:django
    command: python /www/capybara_nori/manage.py runserver 0.0.0.0:8000


