# Generated by Django 4.2.3 on 2023-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='user_description'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_icon_path'),
        ),
    ]
