# Generated by Django 4.2.3 on 2023-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_description_user_user_icon_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon_path',
            field=models.CharField(blank=True, default='defaulticon.png', max_length=255, null=True, verbose_name='user_icon_path'),
        ),
    ]
