# Generated by Django 4.2.3 on 2023-09-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_icon_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_icon_path',
        ),
    ]
