# Generated by Django 4.2.3 on 2023-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupselectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(error_messages={'required': 'test'}, max_length=30)),
                ('Owner', models.CharField(max_length=100000)),
                ('Description', models.TextField(blank=True)),
                ('MemberCount', models.IntegerField(default=1)),
            ],
        ),
    ]
