# Generated by Django 4.2.3 on 2023-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('mail_adress', models.EmailField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=100)),
                ('password_re', models.CharField(max_length=100)),
            ],
        ),
    ]
