# Generated by Django 4.2.3 on 2023-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_BBS', '0006_rooms_roomid_instant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomID_Instant',
            field=models.CharField(max_length=30),
        ),
    ]
