# Generated by Django 4.2.3 on 2023-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sent_room_id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
