# Generated by Django 4.2.3 on 2023-08-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_BBS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='password',
            new_name='passwordInstant',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='username',
            new_name='usernameInstant',
        ),
    ]
