# Generated by Django 4.2.3 on 2023-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_BBS', '0002_rename_password_useraccount_passwordinstant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='passwordInstant',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='usernameInstant',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='older_message',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='roomHost_Instant',
            field=models.CharField(default='host', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='roomMember_Instant',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
