# Generated by Django 4.2.3 on 2023-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_BBS', '0003_remove_useraccount_passwordinstant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomHost_Instant', models.CharField(max_length=50)),
                ('roomMember_Instant', models.IntegerField()),
                ('older_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
