# Generated by Django 4.2.3 on 2023-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_BBS', '0004_rooms_delete_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='roomName_Instant',
            field=models.CharField(default='roomname', max_length=30),
            preserve_default=False,
        ),
    ]
